name: new_project

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  animate_do:
  table_calendar:
  fluttertoast:
  shared_preferences:
  http:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  sqflite:
  path:
  intl:
  dio:
  googleapis_auth:
  firebase_messaging:
  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/doctor_image.jpg
    - assets/Clinic-project-5e77d.json
